import "@/styles/global.css";
import type { Metadata } from "next";
import { MyraidProFont } from "@/font/fonts";
import SessionWrapper from "@/components/session-wrapper/session-wrapper";

export const metadata: Metadata = {
	title: "Fertility Connect App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionWrapper>
			<html lang="en">
				<body className={MyraidProFont.className}>
					{children}
				</body>
			</html>
		</SessionWrapper>
	);
}
